spec:
  template:
    spec:
      serviceAccountName: jdg-springboot-xdc-sa
      containers:
      - name: jdg-springboot-xdc
        env:
        - name: SPRING_CONFIG_LOCATION
          value: file:/etc/config/
        - name: INFINISPAN_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: INFINISPAN_MACHINE
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: JGROUPS_TCP_BIND_ADDRESS
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: JGROUPS_RELAY2_TCP_BIND_ADDRESS
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: JGROUPS_RELAY2_TCP_EXTERNAL_ADDRESS
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        resources:
          requests:
            cpu: "1.0"
          limits:
            cpu: "4.0"
        volumeMounts:
        - name: jdg-springboot-xdc-configmap-vol
          mountPath: /etc/config
          readOnly: true
      volumes:
      - name: jdg-springboot-xdc-configmap-vol
        configMap:
          name: jdg-springboot-xdc-configmap
            