metadata:
  name: jdg-springboot-xdc-tcpping
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  - name: tcpping
    port: 7900
    protocol: TCP
    targetPort: 7900
  - name: kubeping
    port: 8888
    protocol: TCP
    targetPort: 8888