# Servlet Container & Health Setup
server:
  address: 0.0.0.0
management:
  address: 0.0.0.0
  port: 8081
endpoints:
  enabled: false
  health:
    enabled: true
    
# Spring Boot
spring:

# Logging
logging:
  config: classpath:logback.xml
  level:
    #org.infinispan: DEBUG

# Infinispan
infinispan:
  config-file: infinispan.xml
  site: site1
  machine: machine1
  rack: rack1
  node-name: node1
  num-owners: 1

# JGroups
jgroups:
  config-file: jgroups.xml
  tcp:
    bind-address: 127.0.0.1
    bind-port: 7800
    #external-address: 192.168.99.1
    #external-port: 7800
  tcpping:
    initial-hosts: 127.0.0.1[7800]
  relay2:
    config-file: relay.xml
    jgroups-config-file: jgroups-relay.xml
    tcp:
      bind-address: 127.0.0.1
      bind-port: 7900
      external-address: 192.168.99.1
      external-port: 7900
    tcpping:
      initial-hosts: 127.0.0.1[7900]
    
    