apiVersion: "v1"
kind: "ConfigMap"
metadata:
  name: jdg-springboot-xdc-configmap
data:
  java-options: "-Djava.net.preferIPv4Stack=true -Djgroups.tcpping.initial_hosts=127.0.0.1[7800]"
  application.properties: |-
    logging.level.org.infinispan: INFO